### ISSUE TITLE
Reformat code

### ISSUE THREAD

**Issue by JENOT-ANT** [JENOT-ANT/gravity-simulation#10]
- Reformat huge if-statements in: ***gravity-engine.py > Window > get_events*** to more legible form.
- Divide ***gravity-engine.py > Simulation*** to smaller classes (maybe).

**Comment by 9gl** [comment]
Hey @JENOT-ANT  , I'm interested in contributing to this issue. Could you assign me this issue

**Comment by JENOT-ANT** [comment]
Yea, sure.
